#for production 
# version: "3.8"

# services:
#   tube-detector:
#     build: .
#     container_name: tube_system
#     restart: always
#     privileged: true
#     ports:
#       - "8000:8000"
#     devices:
#       - "/dev/video0:/dev/video0"   # for camera support on Pi
#     volumes:
#       - ./dataset:/app/dataset
#       - ./models:/app/models
