# FROM arm64v8/python:3.11-slim

# WORKDIR /app

# # Install dependencies
# COPY requirment.txt /app/
# RUN pip install --no-cache-dir -r requirment.txt

# # Install TFLite Runtime ARM64
# RUN pip install https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.14.0-cp311-cp311-linux_aarch64.whl

# # Export model and run files
# COPY . /app/

# # Expose FastAPI port
# EXPOSE 8000

# CMD ["bash", "run_all.sh"]
